### ISSUE TITLE
Publish InfiniBand SR-IOV CNI image to GCR

### ISSUE THREAD

**Issue by e0ne** [k8snetworkplumbingwg/ib-sriov-cni#59]
Let's make GCR our official registry for IB SR-IOV CNI images like we've got for other projects inside K8S Network Plumbing WG: https://github.com/orgs/k8snetworkplumbingwg/packages.

This will allow us to automatically publish new images to registry and users will have official public repo with new versions

**Comment by adrianchiris** [comment]
+1 on the suggestion !

**Comment by e0ne** [comment]
@adrianchiris @moshe010 we need to publish a new release (e.g. v1.0.2) to publish images

**Comment by e0ne** [comment]
https://github.com/k8snetworkplumbingwg/ib-sriov-cni/pkgs/container/ib-sriov-cni is available
