### ISSUE TITLE
Release ib-sriov-cni v1.0.2

### ISSUE THREAD

**Issue by e0ne** [k8snetworkplumbingwg/ib-sriov-cni#61]
There is a security [fix merged](https://github.com/k8snetworkplumbingwg/ib-sriov-cni/compare/v1.0.1...master) since the last release . It would be good to make a new release to use it in SR-IOV Network Operator

**Comment by adrianchiris** [comment]
ib-sriov-cni[ v1.0.2](https://github.com/k8snetworkplumbingwg/ib-sriov-cni/releases/tag/v1.0.2) has been released.
