### ISSUE TITLE
Release ib-sriov-cni v1.0.3

### ISSUE THREAD

**Issue by almaslennikov** [k8snetworkplumbingwg/ib-sriov-cni#69]
There is a [fix](https://github.com/k8snetworkplumbingwg/ib-sriov-cni/pull/67) merged since the last release that we would like to incorporate in the upcoming network-operator release.

So, requesting to make a new release of ib-sriov-cni

**Comment by e0ne** [comment]
Do we want to have #70 merged for this release and bump version to 1.1?

**Comment by adrianchiris** [comment]
sure

**Comment by adrianchiris** [comment]
v1.0.3 was released !
